### ISSUE TITLE
Install Error on Heroku

### ISSUE THREAD

**Issue by peoute** [Twilio-org/rapid-response-kit#17]
I've tried installing with the Heroku button and through the Heroku CLI from a local copy, but I get this error and it fails to compile.

         > 
          Python app detected
         -----> Installing python-2.7.13
         -----> Installing pip
         -----> Installing requirements with pip

----------------------deleted successful requirement installs-------------------------

         Running setup.py install for twilio: started
           Running setup.py install for twilio: finished with status 'error'
           Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gcj6ra/twilio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aGfXnN-record/install-record.txt --single-version-externally-managed --compile:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-gcj6ra/twilio/setup.py", line 58, in <module>
               License """ )
             File "/app/.heroku/python/lib/python2.7/distutils/core.py", line 111, in setup
               _setup_distribution = dist = klass(attrs)
             File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 321, in __init__
               _Distribution.__init__(self, attrs)
             File "/app/.heroku/python/lib/python2.7/distutils/dist.py", line 287, in __init__
               self.finalize_options()
             File "/app/.heroku/python/lib/python2.7/site-packages/setuptools/dist.py", line 387, in finalize_options
               ep.require(installer=self.fetch_build_egg)
             File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
               items = working_set.resolve(reqs, env, installer, extras=self.extras)
             File "/app/.heroku/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
               raise VersionConflict(dist, req).with_context(dependent_req)
           pkg_resources.VersionConflict: (six 1.5.2 (/tmp/build_42e3afdd5bea3f3af5a97e37d966cd01/Twilio-org-rapid-response-kit-e8fe503/.heroku/python/lib/python2.7/site-packages), Requirement.parse('six>=1.6.0'))
           
           ----------------------------------------
       Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gcj6ra/twilio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aGfXnN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gcj6ra/twilio/
         !     Push rejected, failed to compile Python app.
         !     Push failed
         ----->

**Comment by kwhinnery** [comment]
In the process of migrating this project to run on Twilio Functions, so we probably won't be debugging Heroku deploys going forward. Sorry for the troubles :(
