### ISSUE TITLE
Error deploying to Dokku

### ISSUE THREAD

**Issue by cromulus** [Twilio-org/rapid-response-kit#20]
Dokku is a self-hosted heroku...

```-----> Waiting for 10 seconds ...

remote: App container failed to start!!
=====> rapidresponse web container output:
       2017-07-26 19:19:23 [12] [INFO] Starting gunicorn 18.0
       2017-07-26 19:19:23 [12] [INFO] Listening at: http://0.0.0.0:5000 (12)
       2017-07-26 19:19:23 [12] [INFO] Using worker: sync
       2017-07-26 19:19:23 [141] [INFO] Booting worker with pid: 141
       2017-07-26 19:19:23 [141] [ERROR] Exception in worker process:
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
           worker.init_process()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 106, in init_process
           self.wsgi = self.app.wsgi()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 114, in wsgi
           self.callable = self.load()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
           return self.load_wsgiapp()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
           return util.import_app(self.app_uri)
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 354, in import_app
           __import__(module)
         File "/app/rapid_response_kit/app.py", line 5, in <module>
           from rapid_response_kit.tools import (
         File "/app/rapid_response_kit/tools/volunteer_signup.py", line 4, in <module>
           import gdata.docs.data
         File "/app/.heroku/python/lib/python3.6/site-packages/gdata/__init__.py", line 27, in <module>
           import atom
         File "/app/.heroku/python/lib/python3.6/site-packages/atom/__init__.py", line 133, in <module>
           CreateClassFromXMLString)
         File "/app/.heroku/python/lib/python3.6/site-packages/atom/__init__.py", line 97, in mark_deprecated
           optional_warn_function.func_name = f.func_name
       AttributeError: 'function' object has no attribute 'func_name'
       Traceback (most recent call last):
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
           worker.init_process()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 106, in init_process
           self.wsgi = self.app.wsgi()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 114, in wsgi
           self.callable = self.load()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
           return self.load_wsgiapp()
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
           return util.import_app(self.app_uri)
         File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 354, in import_app
           __import__(module)
         File "/app/rapid_response_kit/app.py", line 5, in <module>
           from rapid_response_kit.tools import (
         File "/app/rapid_response_kit/tools/volunteer_signup.py", line 4, in <module>
           import gdata.docs.data
         File "/app/.heroku/python/lib/python3.6/site-packages/gdata/__init__.py", line 27, in <module>
           import atom
         File "/app/.heroku/python/lib/python3.6/site-packages/atom/__init__.py", line 133, in <module>
           CreateClassFromXMLString)
         File "/app/.heroku/python/lib/python3.6/site-packages/atom/__init__.py", line 97, in mark_deprecated
           optional_warn_function.func_name = f.func_name
       AttributeError: 'function' object has no attribute 'func_name'
```

**Comment by kwhinnery** [comment]
We're preparing a migration of this functionality from Heroku/Python to Twilio Functions, so closing this. Sorry for the troubles and delayed response!
